/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"

#include <Stm32_f103_c6_GPIO_Driver.h>
#include "Stm32_f103_c6.h"
#include "keybad.h"
#include "lcd.h"
#include "Stm32_f103_c6_EXTI_Driver.h"

unsigned int flag =0;



void EXTI9_CallBack()
{
	flag=1;
	LCD_WRITE_STRING("IRQ IS HAPPENED");
	wait_ms(1000);


}


void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++){

		for(j=0;j<255;j++);
	}


}

int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();


	EXTI_PinConf_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN =EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_CFG.p_TRQ_CALLBACK =EXTI9_CallBack;
	EXTI_CFG.IRQ_EN  =EXTI_TRQ_ENABLE;

	MCAL_EXTI_GPIO_INIT(&EXTI_CFG);
	flag =1;






	while (1)
	{
		if(flag)
		{
			LCD_clear_screen();
			flag=0;

		}



	}




}









